name: Compute image tags
description: Compute the tag to use when uploading images
inputs:
  helmdir:
    description: 'Directory of the helm chart to publish'
    required: false
    default: ''
  raw_version_on_branch:
    default: ''
outputs:
  tag:
    description: "The tag to use"
    value: ${{ steps.buildtag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - uses: rlespinasse/slugify-value@v1.x
      with:
        key: GITHUB_REF_NAME
        prefix: CI_
    - id: buildtag
      run: |
        tag="$("${{ github.action_path }}/script.sh" "${{ inputs.helmdir }}" "${{ inputs.raw_version_on_branch }}")"
        if test -z "${tag}"
        then
            exit 1
        else
            echo "tag=${tag}" >> $GITHUB_OUTPUT
        fi
      shell: bash
