#!/bin/bash

set -e

helmdir=$1

if [ -z "$helmdir" ]; then
  if [ -z "$CI_COMMIT_TAG" ]; then
    echo $CI_COMMIT_REF_SLUG.$CI_PIPELINE_IID
  else
    echo $CI_COMMIT_TAG
  fi
else
  version=`yq eval .version $helmdir/Chart.yaml`
  if [ -z "$CI_COMMIT_TAG" ]; then
    version=$version-$CI_COMMIT_REF_SLUG
    echo $version.$CI_PIPELINE_IID
  else
    if [ "$version" != "$CI_COMMIT_TAG" ]; then
      echo Chart version and tag mismatch: "$version" vs "$CI_COMMIT_TAG" >> /dev/stderr
      exit 1
    fi
    echo $version
  fi
fi
