name: Init
description: Setup the default job configuration
inputs:
  helmdir:
    description: 'Directory of the helm chart to publish'
    required: false
    default: ''
  dockerhub_username:
    required: true
    default: ''
  dockerhub_token:
    required: true
    default: ''
outputs:
  tag:
    description: "The tag to use"
    value: ${{ steps.buildtag.outputs.tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: Install earthly
    uses: earthly/actions-setup@79c1a7ec26c371d868724182ec98d7434b18521f # the last tag v1.0.1 does not deal with range for now
    with:
      version: 0.6.*
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
  - uses: eniblock/build/actions/buildtag@main
    id: buildtag
    with:
      helmdir: ${{ inputs.helmdir }}
