#!/bin/bash

set -e

helmdir=$1

version=`yq eval .version $helmdir/Chart.yaml`
if [ -z "$CI_COMMIT_TAG" ]; then
  version=$version-$CI_COMMIT_REF_SLUG
else
  channel=stable
  if [ "$version" != "$CI_COMMIT_TAG" ]; then
    echo Chart version and tag mismatch: "$version" vs "$CI_COMMIT_TAG" >> /dev/stderr
    exit 1
  fi
fi
echo $version
