VERSION 0.6

terraform:
    FROM hashicorp/terraform:1.3.2
    SAVE ARTIFACT /bin/terraform

deps:
    FROM gcr.io/google.com/cloudsdktool/cloud-sdk:405.0.0-alpine
    RUN gcloud components install gke-gcloud-auth-plugin
    RUN apk add \
        bash \
        curl
    COPY +terraform/terraform /usr/local/bin/

RUN:
    COMMAND
    FROM +deps
    WORKDIR /tf
    ARG tfdir=.
    COPY "${tfdir}" ./
    ARG --required environment
    ARG --required command
    ARG options
    ENV GOOGLE_APPLICATION_CREDENTIALS=/tmp/gac.json
    RUN --no-cache \
        --mount type=secret,target=/tmp/gac.json,id=+secrets/gac \
        gcloud auth activate-service-account --key-file /tmp/gac.json \
        && terraform init -input=false \
        && terraform workspace select "$environment" \
        && terraform $command $options

PLAN:
    COMMAND
    ARG --required environment
    DO +RUN --environment "$environment" --command plan

APPLY:
    COMMAND
    ARG --required environment
    DO +RUN  --environment "$environment" --command apply --options "-input=false -auto-approve"
