VERSION 0.6

terraform:
    FROM hashicorp/terraform:1.3.2
    SAVE ARTIFACT /bin/terraform

deps:
    FROM gcr.io/google.com/cloudsdktool/cloud-sdk:405.0.0-alpine
    RUN gcloud components install gke-gcloud-auth-plugin
    RUN apk add \
        bash \
        curl
    COPY +terraform/terraform /usr/local/bin/

TF_APPLY:
    COMMAND
    FROM +deps
    WORKDIR /tf
    ARG tfdir
    COPY "${tfdir}" ./
    ARG environment=dev
    RUN --no-cache --secret google_application_credentials \
        echo "$google_application_credentials" > /tmp/gac \
        && gcloud auth activate-service-account --key-file /tmp/gac \
        && terraform init -input=false \
        && terraform workspace select "$environment" \
        && terraform apply -input=false -auto-approve
