VERSION 0.6

terraform:
    FROM hashicorp/terraform:1.3.2
    SAVE ARTIFACT /bin/terraform

deps:
    FROM gcr.io/google.com/cloudsdktool/cloud-sdk:405.0.0-alpine
    RUN gcloud components install gke-gcloud-auth-plugin
    RUN apk add \
        age \
        bash \
        curl \
        jq
    COPY +terraform/terraform /usr/local/bin/

SETUP:
    COMMAND
    FROM +deps
    WORKDIR /tf
    ARG tfdir=.
    COPY "${tfdir}" ./
    # a first init to cache the plugins
    RUN terraform init -input=false -backend=false
    ARG --required environment
    ENV GOOGLE_APPLICATION_CREDENTIALS=/tmp/gac.json
    RUN --no-cache \
        --mount type=secret,target=/tmp/gac.json,id=+secrets/gac \
        gcloud auth activate-service-account --key-file /tmp/gac.json \
        && terraform init -input=false \
        && { terraform workspace list | grep -q "\b${environment}\b" || terraform workspace new "${environment}" ; } \
        && terraform workspace select "$environment"

RUN:
    COMMAND
    ARG --required command
    ARG options
    ARG output=/dev/stdout
    RUN --no-cache \
        --mount type=secret,target=/tmp/gac.json,id=+secrets/gac \
        terraform $command $options > $output

PLAN:
    COMMAND
    ARG tfdir=.
    ARG --required environment
    DO +SETUP --tfdir $tfdir --environment "$environment"
    DO +RUN --environment "$environment" --command plan

APPLY:
    COMMAND
    ARG tfdir=.
    ARG --required environment
    DO +SETUP --tfdir $tfdir --environment "$environment"
    DO +RUN  --environment "$environment" --command apply --options "-input=false -auto-approve"

OUTPUT:
    COMMAND
    ARG tfdir=.
    ARG --required environment
    DO +SETUP --tfdir $tfdir --environment "$environment"
    DO +RUN  --environment "$environment" --command output
