#!/bin/bash

set -e

image=$1
helmdir=$2
context=${3:-.}
dockerfile=${4:-$context}

dockerhublogin

version=`yq eval .version $helmdir/Chart.yaml`
if [ -z "$CI_COMMIT_TAG" ]; then
  version=$version-$CI_COMMIT_REF_SLUG
  images=$image:$version,$image:$version.$CI_PIPELINE_IID
else
  if [ "$version" != "$CI_COMMIT_TAG" ]; then
    echo Chart version and tag mismatch: "$version" vs "$CI_COMMIT_TAG" >> /dev/stderr
    exit 1
  fi
  images=$image:$version
  short_version=`echo $CI_COMMIT_TAG | sed -E 's/^([0-9]+).([0-9]+).([0-9]+)$/\\1.\\2/'`
  extra_version_opt="--output type=image,name=$image:$short_version,push=true"
fi
if [ "$BUILD_CACHE" == "true" ]; then
  cache_opt="--import-cache type=registry,ref=$image:build-cache"
fi
buildctl-daemonless.sh build \
  --frontend dockerfile.v0 \
  --local context=$context \
  --local dockerfile=$dockerfile \
  --export-cache mode=max,type=registry,ref=$image:build-cache,push=true \
  --secret id=gitlabToken,env=CI_JOB_TOKEN \
  $cache_opt \
  $extra_version_opt \
  --output type=image,\"name=$images\",push=true \
  "${@:5}"
