#!/bin/bash

set -e

image=$1
context=${2:-.}
dockerfile=${3:-$context}

dockerhublogin

if [ -z "$CI_COMMIT_TAG" ]; then
  version=$CI_COMMIT_REF_SLUG
  images=$image:$version,$image:$version.$CI_PIPELINE_IID
else
  short_version=`echo $CI_COMMIT_TAG | sed -E 's/^([0-9]+).([0-9]+).([0-9]+)$/\\1.\\2/'`
  images=$image:$version,$image:$short_version
fi
if [ "$BUILD_CACHE" == "true" ]; then
  cache_opt="--import-cache type=registry,ref=$image:build-cache"
fi
buildctl-daemonless.sh build \
  --frontend dockerfile.v0 \
  --local context=$context \
  --local dockerfile=$dockerfile \
  --export-cache mode=max,type=registry,ref=$image:build-cache,push=true \
  --secret id=gitlabToken,env=CI_JOB_TOKEN \
  $cache_opt \
  --output type=image,\"name=$images\",push=true \
  "${@:4}"
