#!/bin/sh

set -e

image=$1
context=${2:-.}
dockerfile=${3:-.}

if [ -z "$CI_COMMIT_TAG" ]; then
  version=$CI_COMMIT_REF_SLUG
  images=$image:$version,$image:$version.$CI_PIPELINE_IID
else
  images=$image:$CI_COMMIT_TAG
fi
buildctl-daemonless.sh build \
  --frontend dockerfile.v0 \
  --local context=$context \
  --local dockerfile=$dockerfile \
  --export-cache mode=max,type=registry,ref=$image:build-cache,push=true \
  --import-cache type=registry,ref=$image:build-cache \
  --output type=image,\"name=$images\",push=true
