#!/bin/bash

image=$1
helmdir=$2
context=${$2:.}
dockerfile=${$3:.}

version=`yq eval .version $helmdir/Chart.yaml`
if [ -z "$CI_COMMIT_TAG" ]; then
  version=$version-$CI_COMMIT_REF_SLUG
  images=$image:$version,$image:$version.$CI_PIPELINE_IID
else
  [ "$version" != "$CI_COMMIT_TAG" ] && exit 1
  images=$image:$version
fi
buildctl-daemonless.sh build \
  --frontend dockerfile.v0 \
  --local context=$context \
  --local dockerfile=$dockerfile \
  --export-cache mode=max,type=registry,ref=$image:build-cache,push=true \
  --import-cache type=registry,ref=$image:build-cache \
  --output type=image,\"name=$images\",push=true
