VERSION 0.6

vault:
    FROM hashicorp/vault:1.12
    SAVE ARTIFACT /bin/vault

deps:
    FROM alpine/helm:3.10.1
    RUN apk add bash docker-cli
    RUN curl -fsSL https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl > /usr/bin/kubectl \
        && chmod 755 /usr/bin/kubectl
    RUN curl -fsSL https://github.com/vmware-tanzu/carvel-kbld/releases/download/v0.35.0/kbld-linux-amd64 > /usr/bin/kbld \
        && chmod 755 /usr/bin/kbld
    COPY +vault/vault /usr/bin/vault

SETUP:
    COMMAND
    FROM +deps
    RUN --no-cache --secret dockerhub_password \
        echo $dockerhub_password | docker login -u eniblock
    RUN --no-cache --secret github_token \
        echo $github_token | docker login -u eniblock ghcr.io
    RUN --no-cache --secret github_token \
        echo $github_token | helm registry login -u eniblock ghcr.io
