VERSION 0.6

vault:
    FROM hashicorp/vault:1.12
    SAVE ARTIFACT /bin/vault

sops:
    FROM mozilla/sops:v3.7-alpine
    SAVE ARTIFACT /usr/local/bin/sops

crane:
    FROM gcr.io/go-containerregistry/crane:v0.12.1
    SAVE ARTIFACT /ko-app/crane

deps:
    FROM alpine/helm:3.10.1
    RUN apk add age bash docker-cli
    RUN curl -fsSL https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl > /usr/bin/kubectl \
        && chmod 755 /usr/bin/kubectl
    RUN curl -fsSL https://github.com/vmware-tanzu/carvel-kbld/releases/download/v0.35.0/kbld-linux-amd64 > /usr/bin/kbld \
        && chmod 755 /usr/bin/kbld
    RUN curl -fsSL https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_linux_amd64 > /usr/bin/yq \
        && chmod 755 /usr/bin/yq
    COPY +vault/vault /usr/bin/vault
    COPY +sops/sops /usr/bin/sops
    COPY +crane/crane /usr/bin/crane

SETUP:
    COMMAND
    FROM +deps
    WORKDIR /app
    RUN --no-cache --secret dockerhub_token \
        echo $dockerhub_token | docker login -u eniblock --password-stdin
    RUN --no-cache --secret github_token \
        echo $github_token | docker login -u eniblock ghcr.io --password-stdin
    RUN --no-cache --secret github_token \
        echo $github_token | helm registry login -u eniblock ghcr.io --password-stdin

TAG_DEPLOYED:
    COMMAND
    ARG --required repositories
    ARG --required tag
    ARG --required environment
    FOR repository IN ${repositories}
        RUN crane tag ${repository}:${tag} deployed-in-${environment}
    END

TAG_DEPLOYED2:
    COMMAND
    ARG --required images
    ARG --required environment
    FOR image IN ${images}
        RUN crane tag ${image} deployed-in-${environment}
    END
