#!/bin/bash

set -e

helmdir=$1

if [ -z "$helmdir" ]; then
  if [ -z "$COMMIT_TAG" ]; then
    echo $COMMIT_REF_SLUG.$PIPELINE_IID
  else
    echo $COMMIT_TAG
  fi
else
  version=`yq eval .version $helmdir/Chart.yaml`
  if [ -z "$COMMIT_TAG" ]; then
    version=$version-$COMMIT_REF_SLUG
    echo $version.$PIPELINE_IID
  else
    if [ "$version" != "$COMMIT_TAG" ]; then
      echo Chart version and tag mismatch: "$version" vs "$COMMIT_TAG" >> /dev/stderr
      exit 1
    fi
    echo $version
  fi
fi
