name: Setup
description: Setup the default job configuration
inputs:
  helmdir:
    description: 'Directory of the helm chart to publish'
    required: false
    default: ''
  dockerhub_username:
    required: false
    default: 'eniblock'
  dockerhub_token:
    required: true
    default: ''
  default_earthly_cache:
    default: "true"
  fetch-depth:
    default: '1'
  raw_version_on_branch:
    default: ''
  earthly_cache_from_job:
    default: ''
outputs:
  tag:
    description: "The tag to use"
    value: ${{ steps.buildtag.outputs.tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: ${{ inputs.fetch-depth }}
  - name: Install earthly
    uses: earthly/actions-setup@v1.0.4
    with:
      version: 0.7.15
      use-cache: "false"
  - name: Disable earthly analytics
    shell: bash
    run: |
      mkdir -p ~/.earthly
      cat <<EOF > ~/.earthly/config.yml
      global:
        disable_analytics: true
      EOF
  - name: Indicate earthly that the cache is used in http
    shell: bash
    run: |
       earthly config global.buildkit_additional_config "'[registry.\"cache.registry\"]
          http = true'"
  - name: Limit earthly parallelism to 4
    shell: bash
    run: earthly config global.buildkit_max_parallelism 4
  - name: Install python-slugify
    shell: bash
    run: pip install python-slugify
  - name: Slugify some variables
    shell: bash
    run: |
      GITHUB_REF_NAME_SLUG=$(cat <<"EOF" | slugify --max-length 63 --stdin
      ${{ github.ref_name }}
      EOF
      )
      cat <<EOF >> $GITHUB_ENV
      GITHUB_REPOSITORY_SLUG=$(slugify --max-length 63 ${{ github.repository }})
      GITHUB_JOB_SLUG=$(slugify --max-length 63 ${{ github.job }})
      GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG
      EOF
  - name: Export earthly default configuration
    shell: bash
    run: |
      cat <<EOF >> $GITHUB_ENV
      FORCE_COLOR=1
      EARTHLY_NO_OUTPUT=true
      EOF
  - name: Export earthly cache default configuration
    if: inputs.default_earthly_cache == 'true'
    shell: bash
    run: |
      EARTHLY_CACHE_FROM=cache.registry/${GITHUB_REPOSITORY_SLUG}/${GITHUB_JOB_SLUG}:develop
      if [ -n "${{ inputs.earthly_cache_from_job }}" ]; then
          EARTHLY_CACHE_FROM=${EARTHLY_CACHE_FROM},cache.registry/${GITHUB_REPOSITORY_SLUG}/$(slugify --max-length 63 ${{ inputs.earthly_cache_from_job }}):${GITHUB_REF_NAME_SLUG}
      fi
      cat <<EOF >> $GITHUB_ENV
      EARTHLY_MAX_REMOTE_CACHE=true
      EARTHLY_REMOTE_CACHE=cache.registry/${GITHUB_REPOSITORY_SLUG}/${GITHUB_JOB_SLUG}:${GITHUB_REF_NAME_SLUG}
      EARTHLY_CACHE_FROM=${EARTHLY_CACHE_FROM}
      EOF
  - name: Export earthly push default configuration
    if: github.actor != 'dependabot[bot]'
    shell: bash
    run: |
      cat <<EOF >> $GITHUB_ENV
      EARTHLY_PUSH=true
      EOF
  - name: Login to Docker Hub
    if: inputs.dockerhub_token != ''
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
  - name: Login to Docker Hub
    if: env.DOCKERHUB_TOKEN != ''
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ env.DOCKERHUB_TOKEN }}
  - name: Compute the tag to use in this job
    id: buildtag
    shell: bash
    run: |
      helmdir=${HELM_DIR:-${{ inputs.helmdir }}}
      repository=$(basename ${{ github.repository }})
      if [ -z "${helmdir}" ] && [ -d "./helm/${repository}" ]; then
          helmdir=./helm/${repository}
      fi
      tag="$("${{ github.action_path }}/script.sh" "${helmdir}" "${{ inputs.raw_version_on_branch }}")"
      if test -z "${tag}"
      then
          exit 1
      else
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "TAG=${tag}" >> $GITHUB_ENV
      fi
