name: Setup
description: Setup the default job configuration
inputs:
  helmdir:
    description: 'Directory of the helm chart to publish'
    required: false
    default: ''
  dockerhub_username:
    required: false
    default: 'eniblock'
  dockerhub_token:
    required: true
    default: ''
  default_earthly_cache:
    default: "true"
  fetch-depth:
    default: '1'
  raw_version_on_branch:
    default: ''
outputs:
  tag:
    description: "The tag to use"
    value: ${{ steps.buildtag.outputs.tag }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: ${{ inputs.fetch-depth }}
  - name: Install earthly
    uses: earthly/actions-setup@v1
    with:
      version: v0.6.29
  - name: Disable earthly analytics
    shell: bash
    run: |
      mkdir -p ~/.earthly
      cat <<EOF > ~/.earthly/config.yml
      global:
        disable_analytics: true
      EOF
  - name: Indicate earthly that the cache is used in http
    shell: bash
    run: |
       earthly config global.buildkit_additional_config "'[registry.\"cache.registry\"]
          http = true'"
  - name: Export useful common environment variables
    shell: bash
    run: |
      echo "FORCE_COLOR=1" >> $GITHUB_ENV
  - name: Install python-slugify
    shell: bash
    run: pip install python-slugify
  - name: Slugify some variables
    shell: bash
    run: |
      cat <<EOF >> $GITHUB_ENV
      GITHUB_REPOSITORY_SLUG=$(slugify --max-length 63 ${{ github.repository }})
      GITHUB_JOB_SLUG=$(slugify --max-length 63 ${{ github.job }})
      GITHUB_REF_NAME_SLUG=$(slugify --max-length 63 ${{ github.ref_name }})
      EOF
  - name: Export earthly cache default configuration
    if: inputs.default_earthly_cache == 'true'
    shell: bash
    run: |
      cat <<EOF >> $GITHUB_ENV
      EARTHLY_MAX_REMOTE_CACHE=true
      EARTHLY_REMOTE_CACHE=cache.registry/${GITHUB_REPOSITORY_SLUG}/${GITHUB_JOB_SLUG}:${GITHUB_REF_NAME_SLUG}
      EARTHLY_CACHE_FROM=cache.registry/${GITHUB_REPOSITORY_SLUG}/${GITHUB_JOB_SLUG}:develop
      EARTHLY_STRICT=true
      EARTHLY_PUSH=true
      EOF
  - name: Login to Docker Hub
    if: inputs.dockerhub_token != ""
    uses: docker/login-action@v2
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
  - name: Compute the tag to use in this job
    id: buildtag
    shell: bash
    run: |
      tag="$("${{ github.action_path }}/script.sh" "${{ inputs.helmdir }}" "${{ inputs.raw_version_on_branch }}")"
      if test -z "${tag}"
      then
          exit 1
      else
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      fi
