#!/bin/sh

set -e

image=$1
helmdir=$2

version=`yq eval .version $helmdir/Chart.yaml`
if [ -z "$CI_COMMIT_TAG" ]; then
  version=$version-$CI_COMMIT_REF_SLUG
else
  if [ "$version" != "$CI_COMMIT_TAG" ]; then
    echo Chart version and tag mismatch: "$version" vs "$CI_COMMIT_TAG" >> /dev/stderr
    exit 1
  fi
fi
yq e -i ".appVersion = \"$version\"" $helmdir/Chart.yaml
helm chart save ./$helmdir $image:$version
helm chart push $image:$version

if [ -z "$CI_COMMIT_TAG" ]; then
  version=$version.$CI_PIPELINE_IID
  helm chart save $helmdir $image:$version
  helm chart push $image:$version
fi
git checkout HEAD $helmdir/Chart.yaml
