#!/bin/bash

set -e

image=$1
tag=$2

registry_username=$3
registry_password=$4

patch_values=$5

helmdir=helm
appVersion="${tag}"
repository=`dirname $image`

name=`yq eval .name $helmdir/Chart.yaml`
version=`yq eval .version $helmdir/Chart.yaml`
if [ "$name" != `basename $image` ]; then
  echo image and chart name mismatch
  exit 1
fi


# copy the Chart in the safe place
tmp_chart=`mktemp`
cp $helmdir/Chart.yaml $tmp_chart
tmp_values=`mktemp`
cp $helmdir/values.yaml $tmp_values

yq e -i ".version = \"$appVersion\"" $helmdir/Chart.yaml
if [[ "$patch_values" != *"NO_PATCH"* ]]; then
  yq e -i ".appVersion = \"$appVersion\"" $helmdir/Chart.yaml
fi
for path in $patch_values; do
  if [ "$path" != "NO_PATCH" ]; then
    yq e -i "$path = \"$appVersion\"" $helmdir/values.yaml
  fi
done

echo "${registry_password}" | helm registry login "${repository}" -u "${registry_username}" --password-stdin
rm -rf "${helmdir}/charts"
helm dependency update "./${helmdir}"
helm package --version "${version}" "./${helmdir}"
helm push "${name}-${version}.tgz" "oci://${repository}"
