VERSION 0.6

kubeval:
    FROM golang:alpine
    WORKDIR /app
    RUN apk add git make bash patch
    RUN git clone -b 0.16.0 https://github.com/instrumenta/kubeval.git .
    COPY kubeval.patch ./
    RUN patch -p1 < kubeval.patch
    RUN make
    SAVE ARTIFACT /app/bin/kubeval

helmtools:
    FROM alpine:3.15
    RUN apk add \
      bash \
      curl \
      docker-cli \
      bat \
      yamllint \
      util-linux
    RUN wget -q https://github.com/rancher/k3d/releases/download/v4.4.1/k3d-linux-amd64 -O /usr/local/bin/k3d
    RUN wget -q https://dl.k8s.io/release/v1.20.2/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl
    RUN curl -sSL https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz | tar xvzC /usr/local/bin --strip-components=1 linux-amd64/helm
    RUN wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_linux_amd64
    RUN curl -sSL https://github.com/stackrox/kube-linter/releases/download/0.2.5/kube-linter-linux.tar.gz | tar xvzC /usr/local/bin
    COPY +kubeval/kubeval /usr/local/bin/
    COPY master-standalone-strict/ /master-standalone-strict/
    COPY --dir yamllint.yaml kube-linter.yaml /etc/
    COPY build lint /usr/local/bin/
    RUN chmod a+x /usr/local/bin/*

LINT:
    COMMAND
    FROM +helmtools
    WORKDIR /app
    ARG registry=ghcr.io
    ARG login=true
    IF [ "$login" = "true" ]
        RUN --secret registry_username --secret registry_password helm registry login -u "${registry_username}" -p "${registry_password}" "${registry}"
    END
    ARG helmdir
    COPY "${helmdir}/Chart.yaml" ./Chart.yaml
    RUN helm dependency update .
    COPY "${helmdir}" ./
    ARG environment=dev
    RUN lint . --values values-${environment}.yaml

PUBLISH_HELM:
    COMMAND
    FROM +helmtools
    WORKDIR /app
    ARG helmdir
    COPY "${helmdir}" ./helm
    ARG image
    ARG patch_value
    ARG tag=latest
    RUN --secret registry_username --secret registry_password sh /usr/local/bin/build "${image}" "${tag}" "${registry_username}" "${registry_password}" ${patch_value}
