#!/bin/sh

# set -x
set -o pipefail

helm template "$@" > /tmp/k8s.yaml  || exit 1

cd /generated
split-yaml-docs /tmp/k8s.yaml || exit 1

yamls=`find . -name '*.yaml' | tr '\n' ' '`

kubeval ${KUBEVAL_ARGS} --strict --schema-location file:/// $yamls 2>&1 | sed -e 's@÷@/@g' > /tmp/kubeval.out
kubeval_exit=$?

script --return --quiet -c "kube-linter lint --config /etc/kube-linter.yaml $yamls" /dev/null 2>&1 | sed -e 's@÷@/@g' > /tmp/kube-linter.out
kubelinter_exit=$?

yamllint -c /etc/yamllint.yaml -f colored $yamls 2>&1 | sed -e 's@÷@/@g' > /tmp/yamllint.out
yamllint_exit=$?
yamllint_count=`wc -l /tmp/yamllint.out | cut -d ' ' -f1`

yamllint_files=`grep -oE './[^:]+\.yaml' /tmp/yamllint.out | sort | uniq`
kube_linter_files=`grep -oE './[^:]+\.yaml' /tmp/kube-linter.out | sort | uniq`
kubeval_files=`grep "ERR -" /tmp/kubeval.out | grep -oE '[^: ]+\.yaml' | sort | uniq`
files=`echo $kube_linter_files $kubeval_files $yamllint_files | sort | uniq | sed -e 's@/@%@g' | sed -e 's@^\\.%@/generated/@g'`

if [[ $yamllint_exit != 0 || $kubelinter_exit != 0 || $kubeval_exit != 0 || $yamllint_count != 0 ]]; then
  TERM=xterm bat --paging=never --color=always --style=numbers,grid --wrap=never $files
fi

cat /tmp/kubeval.out /tmp/kube-linter.out /tmp/yamllint.out

if [ $yamllint_exit != 0 ]; then
  echo -e '\033[0;31myamllint check failed\033[0m'
fi
if [ $kubelinter_exit != 0 ]; then
  echo -e '\033[0;31mkube-linter check failed\033[0m'
fi
if [ $kubeval_exit != 0 ]; then
  echo -e '\033[0;31mkubeval check failed\033[0m'
fi

if [[ $yamllint_exit != 0 || $kubelinter_exit != 0 || $kubeval_exit != 0 ]]; then
  exit 1
else
  echo -e '\033[0;32mcheck succeeded :)\033[0m'
fi
